[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan storage:link && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && vendor/bin/heroku-php-apache2 public/"
