[phases.setup]
nixPkgs = ["...", "nodejs_20", "php83", "php83Packages.composer"]
aptPkgs = ["...", "chromium", "chromium-driver"]

[phases.install]
cmds = [
    "cd sad",
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci --silent"
]

[phases.build]
cmds = [
    "cd sad",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[deploy]
onSuccessCommand = "cd sad && php artisan migrate --force && php artisan storage:link"

[start]
cmd = "cd sad && php artisan serve --host=0.0.0.0 --port=${PORT}"
